# Generated by Django 4.1.4 on 2023-08-04 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('pcid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pcname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('userid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('usertype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('mob', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('pdesc', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('pcid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('orderid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('orderdate', models.DateField()),
                ('amount', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('orderid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('netprice', models.IntegerField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('compid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('compdesc', models.CharField(max_length=500, null=True)),
                ('compdt', models.DateField(null=True)),
                ('status', models.CharField(default='open', max_length=30)),
                ('response', models.CharField(default='Response Awaited', max_length=400, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usermaster')),
            ],
        ),
    ]
